name: flutterhole
description: A new Flutter application.

version: 2.0.3+205

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.7
  equatable: ^0.2.6
  bloc: ^0.14.4
  flutter_bloc: ^0.19.1
  fimber: ^0.3.0
  fluro: ^1.5.0
  shared_preferences: ^0.5.3+1
  url_launcher: ^5.0.3
  launch_review: ^2.0.0
  package_info: ^0.4.0+4
  flutter_form_builder: ^3.2.0
  persist_theme: ^1.5.1
  flutter_picker: ^1.0.13
  flutter_markdown: ^0.2.0
  qrcode_reader: ^0.4.4
  sticky_headers: ^0.1.8
  provider: ^3.0.0+1
  fl_chart: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  mockito: ^4.1.0
  flutter_launcher_icons: ^0.7.2+1
  screenshots: ^1.3.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true